[package]
name = "redscript-formatter"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
redscript-ast.workspace = true
redscript-parser.workspace = true

pretty_dtoa.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
