[package]
name = "redscript-dotfile"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true

[lints]
workspace = true
