use std::sync::LazyLock;

use hashbrown::HashSet;

pub struct KnownTypes {
    sealed: HashSet<&'static str>,
    never_ref: HashSet<&'static str>,
}

impl KnownTypes {
    pub fn get() -> &'static Self {
        static INSTANCE: LazyLock<KnownTypes> = LazyLock::new(|| KnownTypes {
            sealed: SEALED_TYPES.iter().copied().collect(),
            never_ref: NEVER_REF_TYPES.iter().copied().collect(),
        });

        &INSTANCE
    }

    pub fn is_sealed(&self, name: &str) -> bool {
        self.sealed.contains(name)
    }

    pub fn is_never_ref(&self, name: &str) -> bool {
        self.never_ref.contains(name)
    }
}

const NEVER_REF_TYPES: &[&str] = &["ReactionData"];

// generated with https://github.com/jac3km4/redscript-sealed-struct-dumper
// this is a list of native structs that are fully exposed to scripts
const SEALED_TYPES: &[&str] = &[
    "AIActiveCommandList",
    "AICommandNodeFunction",
    "AIDelegateAttrRef",
    "AIDelegateTaskRef",
    "AIScriptUtils",
    "AVSpawnPointsRequestResult",
    "ActionDisplayData",
    "ActionPrereqs",
    "AmmoData",
    "AttackDebugData",
    "AttackInitContext",
    "BinkVideoSummary",
    "Box",
    "BuffInfo",
    "CachedBoolValue",
    "CharacterCustomizationAttribute",
    "CharactersChain",
    "ChatBoxText",
    "Color",
    "CombatSpaceHelper",
    "ComputerUIData",
    "ContextDisplayData",
    "ControllerHit",
    "CustomQuestNotificationData",
    "DSSSpawnRequestResult",
    "DamageInfo",
    "DebugDrawer",
    "DelayID",
    "DialogChoiceHubs",
    "DismemberedLimbCount",
    "DropInstruction",
    "EffectData",
    "EffectDurationModifierScriptContext",
    "EffectExecutionScriptContext",
    "EffectInfo",
    "EffectPreloadScriptContext",
    "EffectProviderScriptContext",
    "EffectScriptContext",
    "EffectSingleFilterScriptContext",
    "EngineTime",
    "EntityGameInterface",
    "EntityRequestComponentsInterface",
    "EntityResolveComponentsInterface",
    "EnumNameToIndexCache",
    "FragmentBuilder",
    "Frustum",
    "GOGRewardPack",
    "GameInstance",
    "GenericDataContent",
    "GetActionsContext",
    "HDRColor",
    "HandIKDescriptionResult",
    "HandleWithValue",
    "HitRepresentationQueryResult",
    "HitShapeResult",
    "IKTargetRef",
    "IMappinData",
    "ImpactPointData",
    "InnerItemData",
    "InputHintGroupData",
    "InputTriggerState",
    "InteractionChoiceCaption",
    "InteractionChoiceData",
    "InteractionChoiceHubData",
    "InteractionChoiceMetaData",
    "InteractionLayerData",
    "InventoryItemAbility",
    "InventoryItemSortData",
    "JournalFactNameValue",
    "JournalRequestStateFilter",
    "KillInfo",
    "LevelUpData",
    "LightPreset",
    "ListChoiceData",
    "ListenerAction",
    "ListenerActionConsumer",
    "LocationInformation",
    "LookAtLimits",
    "LookAtPartRequest",
    "LookAtRef",
    "LootVisualiserControlWrapper",
    "MappinUIProfile",
    "MappinUIUtils",
    "MappinUtils",
    "Matrix",
    "MeasurementUtils",
    "MinigameProgramData",
    "MotionConstrainedTierDataParams",
    "MountingInfo",
    "MountingSlotId",
    "MovementParameters",
    "NPCstubData",
    "NarrationEvent",
    "NarrativePlateData",
    "NavigationFindPointResult",
    "NearestRoadFromPlayerInfo",
    "NewMappinID",
    "PhotoModeOptionGridButtonData",
    "PinInfo",
    "PlayerBioMonitor",
    "PrereqCheckData",
    "PrereqData",
    "PrereqParams",
    "PreventionSystemDebugData",
    "Quaternion",
    "RWLock",
    "Range",
    "RectF",
    "RegisterCooldownFromRecordRequest",
    "RegisterNewCooldownRequest",
    "RemoteControlDrivingUIData",
    "RestrictMovementArea",
    "SDOSink",
    "SEquipArea",
    "SEquipSlot",
    "SEquipmentSet",
    "SItemInfo",
    "SItemStack",
    "SItemStackRequirementData",
    "SLastUsedWeapon",
    "SLoadout",
    "SPartSlots",
    "SSlotActiveItems",
    "SSlotInfo",
    "SSlotVisualInfo",
    "SVisualTagProcessing",
    "ScanningTooltipElementData",
    "ScanningTooltipElementDef",
    "ScriptExecutionContext",
    "SecureFootingResult",
    "SlotWeaponData",
    "SnapshotResult",
    "Sphere",
    "SquadOrder",
    "StatViewData",
    "StateMachineIdentifier",
    "StateMachineInstanceData",
    "StatusEffectTDBPicker",
    "StimuliMergeInfo",
    "TDBID",
    "TS_TargetPartInfo",
    "TacticRatio",
    "TargetFilterTicket",
    "TargetSearchFilter",
    "TelemetryDamageDealt",
    "TelemetryEnemy",
    "TelemetryEnemyDown",
    "TelemetryInventoryItem",
    "TelemetryLevelGained",
    "TelemetryQuickHack",
    "TelemetrySourceEntity",
    "TraceResult",
    "Transform",
    "TrialHelper",
    "TutorialBracketData",
    "UIScreenDefinition",
    "UnlockableProgram",
    "Vector2",
    "Vector3",
    "Vector4",
    "VendorData",
    "VideoWidgetSummary",
    "VisionBlockerTypeFlags",
    "VisualizersInfo",
    "WeakspotPhysicalDestructionComponent",
    "WeakspotPhysicalDestructionProperties",
    "WeaponRosterInfo",
    "WidgetUtils",
    "WorkEntryId",
    "WrappedEntIDArray",
    "bbUIInteractionData",
    "gameGrenadeThrowQueryParams",
    "gamePendingSubtitles",
    "gameSaveLock",
    "gameStatDetailedData",
    "gameSuggestedDefenseValues",
    "gameVisionModeSystemRevealIdentifier",
    "gameinteractionsActiveLayerData",
    "gamemappinsSenseCone",
    "gameprojectileLaunchParams",
    "gameuiDetectionParams",
    "gameuiDriverCombatCrosshairReticleData",
    "gameuiGenericNotificationData",
    "gameuiMountedWeaponTarget",
    "gameuiPatchIntroPackage",
    "gameuiSwitchPair",
    "gameuiWeaponShootParams",
    "inkInputKeyData",
    "inkMargin",
    "inkScreenProjectionData",
    "inkWidgetLibraryReference",
    "questPaymentConditionData",
    "scnDialogDisplayString",
    "scnDialogLineData",
    "smartGunUISightParameters",
    "smartGunUITargetParameters",
    "vehicleUnmountPosition",
    "worldTrafficLaneRef",
];
