name: CI

on:
  push:
    branches: ["*.*.x"]
  pull_request:

jobs:
  check-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal --component rustfmt --no-self-update
      - run: cargo +nightly fmt --all -- --check

  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component clippy --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings

  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  package:
    name: Build and package
    uses: ./.github/workflows/package.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
        include:
          - os: windows-latest
            suffix: windows
          - os: macos-14
            suffix: macos
    with:
      os: ${{ matrix.os }}
      suffix: ${{ matrix.suffix }}
      tag: ${{ github.base_ref || github.ref_name }}
