name: CI

on:
  push:
    branches: ["*.*.x"]
  pull_request:
    branches: ["*.*.x"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal --component rustfmt --no-self-update
      - run: cargo +nightly fmt --all -- --check

  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component clippy --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings

  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  package:
    name: Package and upload artifacts
    uses: ./.github/workflows/package.yml
