on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      suffix:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ inputs.os }}
      - run: cargo build --release

      - id: tag-win
        if: runner.os == 'Windows'
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $env:GITHUB_OUTPUT
      - id: tag-unix
        if: runner.os != 'Windows'
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - if: runner.os == 'Windows'
        run: .\scripts\package.ps1 -archiveName "redscript-${{ steps.tag.outputs.tag-win }}-${{ inputs.suffix }}.zip"
      - if: runner.os != 'Windows'
        run: ./scripts/package.sh "redscript-${{ steps.tag.outputs.tag-unix }}-${{ inputs.suffix }}.zip"

      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          path: |
            redscript-cli.exe
            redscript-cli-aarch64-darwin
            redscript-cli-x86_64-linux-gnu
            redscript-${{ steps.get-tag-win.outputs.tag || steps.get-tag-unix.outputs.tag }}-${{ inputs.suffix }}.zip
          name: artifact-${{ inputs.os }}
          if-no-files-found: error
