on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: windows-latest
    env:
      ARCHIVE_NAME: redscript-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: .\build\package.ps1 -zipPath ${{ env.ARCHIVE_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ env.ARCHIVE_NAME }}
            target/release/redscript-cli.exe
          if-no-files-found: error
