name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    name: Package and upload artifacts
    uses: ./.github/workflows/package.yml

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: package
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FLAGS=()
          ARTIFACTS=$(find ./artifacts -type f)

          if echo ${{ github.ref_name }} | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+-.+'; then
            FLAGS+=(--prerelease)
          fi

          gh release create ${{ github.ref_name }} ${FLAGS[@]} $ARTIFACTS
