name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  package:
    name: Build and package
    uses: ./.github/workflows/package.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
        include:
          - os: windows-latest
            suffix: windows
          - os: macos-14
            suffix: macos
    with:
      os: ${{ matrix.os }}
      suffix: ${{ matrix.suffix }}

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: package
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FLAGS=()
          ARTIFACTS=$(find ./artifacts -type f)

          if echo ${{ github.ref_name }} | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+-.+'; then
            FLAGS+=(--prerelease)
          fi

          gh release create ${{ github.ref_name }} ${FLAGS[@]} $ARTIFACTS
